- lib/node-debugger.coffee
Minor, minor follow up on the config fix.
> Support windows launch by default

- demo/a.js
- lib/Components/ConsolePane.coffee
Fix for https://github.com/kiddkai/atom-node-debugger/issues/52
Included slight update of a.js to include array variables. Hope that is ok.
> Bugfix: Execution of invalid code in console causes crash

- demo/a.js
- lib/Components/ConsolePane.coffee
- lib/Components/consolepane-utils.coffee
- spec/src/consolepane-utils-spec.coffee
I think this is a convenient feature. Hope you also think so. :)
> Command history for console pane implemented

- lib/debugger.coffee
- package.json
Fix Issue #50 by using tree-kill instead of psTree + spawn(kill).
Tested and works on windows.
> Fix Issue #50

- lib/debugger.coffee
fix issue for https://github.com/kiddkai/atom-node-debugger/issues/49
> fix issue #49

- README.md
is set correctly, otherwise the debugger will not work
> README enhancement: first check that the node path

- lib/Components/ConsolePane.coffee
Found solution here: https://github.com/tcarlsen/atom-message-panel/issues/24
> Enabled console text selection

- lib/debugger.coffee
I broke process cwd during earlier commit
> Bugfix process cwd regression

- lib/Components/BreakPointPane.coffee
- lib/Components/ConsolePane.coffee
- lib/debugger.coffee
- lib/eventing.coffee
- lib/node-debugger.coffee
- spec/src/eventing-spec.coffee
- styles/node-debugger.less
Keep track of breakpoints when disconnected from node so that the user does not need to set them up for each debug session.
> Improved breakpoint management

- README.md
- lib/Components/ConsolePane.coffee
- lib/debugger.coffee
- lib/node-debugger.coffee
> Attach to external process now supported

- menus/node-debugger.cson
Missed menu option for attach to process (#23)
> Added attach command to menu

- lib/Components/ConsolePane.coffee
as suggested by @codyhazelwood in #128
> console monospace

- lib/Components/CallStackPane.coffee
Implementation of feature request #144
> Sort locals alphabetically

- demo/a.js
- lib/Components/CallStackPane.coffee
Implemented feature request #143
> 'this' is now available in Locals

- lib/Components/CancelButton.coffee
- lib/debugger.coffee
- lib/node-debugger.coffee
> Fix shutdown behaviour

- demo/a.js
- lib/Components/CallStackPane.coffee
> #158: Special treatment of Date objects in watch window implemented.

- lib/node-debugger.coffee
Removed the implementation for now. Do not think it was doing much good.
> Fixed problem with serialization crash #165

- lib/Components/App.coffee
- lib/Components/CallStackPane.coffee
- lib/Components/TreeView.coffee
- lib/Components/focus-hook.js
Watch window enables continuous evaluation of custom expressions
> Implemented watch window

- lib/Components/App.coffee
- lib/Components/BreakPointPane.coffee
- lib/Components/CallStackPane.coffee
> Bugfix event leaks

- lib/Components/CallStackPane.coffee
Example :
> objTest: Object { ... }
> testArr: Array [ 16 ]
> Better array visualization, #166

- lib/Components/CancelButton.coffee
Make cancel button look like other buttons (start, next step, step in, step out).
> Improve cancel button look

- lib/Components/App.coffee
- lib/Components/ConsolePane.coffee
- lib/node-debugger-view.coffee
Better use of screen space. Console pane kept to the bottom; the rest of the panels moved to the right.
> New layout

- lib/Components/CallStackPane.coffee
- styles/node-debugger.less
> Object references implemented #183

- lib/Components/CancelButton.coffee
- lib/Components/ConsolePane.coffee
- lib/Components/StepButton.coffee
- styles/node-debugger.less
- Adding tooltips to the different buttons
- Slight change of the breakpoints colors to make it look less "agressive"
> Tooltips and breakpoints color

- lib/debugger.coffee
Breakpoints now change when new lines are added
> Fixed issue #213

- styles/node-debugger.less
> Fix deprecations #215
